#!/usr/bin/env bash

set -ex

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


docker run \
  -v "${SCRIPT_DIR}/../config.yaml:/etc/otelcol/config.yaml" \
  -e COLLECTOR_OTLP_ENABLED=true \
  -p4318:4318 \
  otel/opentelemetry-collector:0.60.0